# Generated by Django 3.1.1 on 2021-03-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='data',
            field=models.CharField(blank=True, default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='cname',
            field=models.ForeignKey(blank=True, default='none', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcname',
            field=models.CharField(blank=True, default='none', max_length=100, null=True),
        ),
    ]
